name: Bump Helm Chart Version
description: Bump a Helm Chart Version Locally
branding:
  icon: hard-drive
  color: blue
inputs:
  app-version:
    description: to also bump app-version
    default: "false"
    required: false
  level:
    description: patch/minor/major
    required: true
  chart-path:
    description: the directory path to the specified chart (without / at the end)
    required: true
outputs:
  app-version:
    description: "Updated App version"
    value: ${{ steps.app-version-bump.outputs.version }}
  chart:
    description: "Chart name"
    value: ${{ steps.chart-name.outputs.chart }}
  chart-version:
    description: "Updated Chart version"
    value: ${{ steps.chart-version-bump.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Install PyBump
      run: |
        python3 -m pip install pybump
      shell: bash
    - name: Bump App Version
      id: app-version-bump
      run: |
        version=$(pybump bump --file ${{ inputs.chart-path }}/Chart.yaml --level ${{ inputs.level }} --app-version)
        echo "version=$version" >> $GITHUB_OUTPUT
      if: inputs.app-version == 'true'
      shell: bash
    - name: Automated Version Bump
      id: chart-version-bump
      run: |
        version=$(pybump bump --file ${{ inputs.chart-path }}/Chart.yaml --level ${{ inputs.level }})
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "CHART_VERSION=$version" >> $GITHUB_ENV
      shell: bash
    - name: Output Name
      id: chart-name
      run: |
        echo "chart=$(basename ${{ inputs.chart-path }})" >> $GITHUB_OUTPUT
      shell: bash
